### ISSUE TITLE
Preview/Edit Mode for Highlighting settings different

### ISSUE THREAD

**Issue by Fayneloves** [mgmeyers/obsidian-style-settings#67]
![image](https://user-images.githubusercontent.com/86388692/165278970-2c7e2e1a-dafd-424a-8e94-b3f9acd8e4fa.png)

Hello there!

Appreciate your effort on making Obsidian ever more user-friendly, especially to programming-idiots like me. I really like the feature of different highlighting colors for different emphasis and realised that there was an issue when I went on to Preview mode. I guess it still took the 'standard' settings on it and unsure how else can I work around this?

As I'm programming challenged, if there is a work-around with the CSS import feature with Style Settings, pls do share !

**Comment by damiankorcz** [comment]
@Fayneloves This issue appears to be related to your theme rather than Style Settings specifically. Style Settings serves as a framework for theme developers to specify settings that display in Style Settings from their Theme's CSS. It doesn't give the end user any settings by default. It's entirely up to the theme dev. Judging by the screenshot you are using Primary theme. This is it's repository: https://github.com/ceciliamay/obsidianmd-theme-primary
